# fly.toml app configuration file generated for fast-six-violet on 2025-02-11T08:40:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[build]
  image = 'mysql:8'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="mysql_data"
  destination="/var/lib/mysql"
