name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

    steps:
      - name: Copiar os arquivos
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar o poetry
        run: pip install poetry

      - name: Instalando as dependências
        run: |
          cd fast_six
          poetry install

      - name: Subir banco MySQL para testes
        run: |
          docker run \
            --name app_database \
            -e MYSQL_ROOT_PASSWORD=root_password \
            -e MYSQL_USER=app_user \
            -e MYSQL_PASSWORD=app_password \
            -e MYSQL_DATABASE=app_db \
            -p 3307:3306 \
            -d mysql:8.0


      - name: Testes
        run: |
          cd fast_six
          poetry run task test